const dummyData = [
   { region: 'East Los Angeles',
    parks: [ {
      name: 'El Sereno Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/ElSereno/el-sereno-skate-park-1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/ElSereno/el-sereno-skate-park-3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/ElSereno/el-sereno-skate-park-4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/ElSereno/el-sereno-skate-park-5.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/ElSereno/el-sereno-skate-park-6.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/ElSereno/el-sereno-skate-park-7.jpg',
              ],
      address: {
        street: '4721 Klamath Place',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90032'
      },
      region: 'eastLA',
      website: 'https://www.laparks.org/skatepark/el-sereno-skate',
      phone: '(323) 225-3517',
      latitude: '34.0757',
      longitude: '-118.182',
      geolong: '-118.1815698',
      geolat: '34.075694',
      reviews: [],
      rating: null,
    },
    {
      name: 'Garvanza Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/Garvanza/garvanza1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/Garvanza/garvanza2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/Garvanza/garvanza3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/Garvanza/garvanza4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/Garvanza/garvanza5.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/Garvanza/garvanza6.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/Garvanza/garvanza7.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/Garvanza/garvanza8.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/Garvanza/garvanza9.jpg',
              ],
      address: {
        street: '6240 Meridian St',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90042'
      },
      region: 'eastLA',
      website: 'https://www.laparks.org/skatepark/garvanza-skate',
      phone: '(323) 255-0370',
      latitude: '34.1201',
      longitude: '-118.18',
      geolong: '-118.179944',
      geolat: '34.12007',
      reviews: [],
      rating: null,
    },
    {
      name: 'Gilbert W. Lindsay Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/GilbertLindsay/gilbertlindsay1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/GilbertLindsay/gilbertlindsay2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/GilbertLindsay/gilbertlindsay3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/GilbertLindsay/gilbertlindsay4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/GilbertLindsay/gilbertlindsay5.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/GilbertLindsay/gilbertlindsay6.jpg',
              ],
      address: {
        street: '429 East 42nd Place',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90011'
      },
      region: 'eastLA',
      website: 'https://www.laparks.org/skatepark/gilbert-lindsay-skate',
      phone: '(323) 233-0552',
      latitude: '34.0066',
      longitude: '-118.268',
      geolong: '-118.2677641',
      geolat: '34.00661929',
      reviews: [],
      rating: null,
    },
    {
      name: 'Hazard Park Skate Plaza',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/HazardSkate/hazard-skate10.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/HazardSkate/hazard-skate1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/HazardSkate/hazard-skate2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/HazardSkate/hazard-skate3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/HazardSkate/hazard-skate4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/HazardSkate/hazard-skate5.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/HazardSkate/hazard-skate6.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/HazardSkate/hazard-skate7.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/HazardSkate/hazard-skate8.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/HazardSkate/hazard-skate9.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/HazardSkate/hazard-skate11.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/HazardSkate/hazard-skate12.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/HazardSkate/hazard-skate13.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/HazardSkate/hazard-skate14.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/HazardSkate/hazard-skate15.jpg',
              ],
      address: {
        street: '2230 Norfolk St',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90033'
      },
      region: 'eastLA',
      website: 'https://www.laparks.org/reccenter/hazard',
      phone: '(213) 485-6839',
      latitude: '',
      longitude: '',
      geolong: '',
      geolat: '',
      reviews: [],
      rating: null,
    },
    {
      name: 'Lincoln Park Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/LincolnPark/lincolnpark1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/LincolnPark/lincolnpark2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/LincolnPark/lincolnpark3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/LincolnPark/lincolnpark4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-eastla/LincolnPark/lincolnpark5.jpg',
              ],
      address: {
        street: '3501 Valley Blvd',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90031'
      },
      region: 'eastLA',
      website: 'https://www.laparks.org/skatepark/lincoln-skate',
      phone: '(213) 847-1726',
      latitude: '34.0656',
      longitude: '-118.202',
      geolong: '-118.2018369',
      geolat: '34.06561417',
      reviews: [],
      rating: null,
    }]
  },
  {
    region: 'Metro',
    parks: [ {
      name: 'Chevy Chase Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-metro/ChevyChase/chevy-chase1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/ChevyChase/chevy-chase2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/ChevyChase/chevy-chase3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/ChevyChase/chevy-chase4.jpg',
              ],
      address: {
        street: '4165 Chevy Chase Drive',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90039'
      },
      region: 'metro',
      website: 'https://www.laparks.org/skatepark/chevy-chase-skate-park',
      phone: '(213) 485-4867',
      latitude: '',
      longitude: '',
      geolong: '',
      geolat: '',
      reviews: [],
      rating: null,
    },
    {
      name: 'Hollenbeck Safe Spot Skate Spot',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-metro/Hollenbeck/hollenbeckskate1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/Hollenbeck/hollenbeckskate2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/Hollenbeck/hollenbeckskate3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/Hollenbeck/hollenbeckskate4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/Hollenbeck/hollenbeckskate5.jpg',
              ],
      address: {
        street: '415 S. Saint Louis St',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90033',
      },
      region: 'metro',
      website: 'https://www.laparks.org/skatepark/hollenbeck-safe-spot-skate-spot',
      phone: '(323) 261-0113',
      latitude: '34.0414',
      longitude: '-118.216',
      geolong: '-118.2160944',
      geolat: '34.04136456',
      reviews: [],
      rating: null,
    },
    {
      name: 'Lake Street Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-metro/LakeStreet/lake-street11.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/LakeStreet/lake-street1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/LakeStreet/lake-street2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/LakeStreet/lake-street3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/LakeStreet/lake-street4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/LakeStreet/lake-street5.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/LakeStreet/lake-street6.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/LakeStreet/lake-street7.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/LakeStreet/lake-street8.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/LakeStreet/lake-street9.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/LakeStreet/lake-street10.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/LakeStreet/lake-street12.jpg',
              ],
      address: {
        street: '227 N. Lake St.',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90026'
      },
      region: 'metro',
      website: 'http://www.laparks.org/skatepark/lake-street-skate',
      phone: '(213) 207-2196',
      latitude: '34.0687',
      longitude: '-118.27',
      geolong: '-118.270384',
      geolat: '34.06874703',
      reviews: [],
      rating: null,
    },
    {
      name: 'Lafayette Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-metro/Lafayette/lafayetteskate1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/Lafayette/lafayetteskate2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/Lafayette/lafayetteskate3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-metro/Lafayette/lafayetteskate4.jpg',
              ],
      address: {
        street: '625 South Lafayette Place',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90057'
      },
      region: 'metro',
      website: 'https://www.laparks.org/skatepark/lafayette-skate',
      phone: '(213) 384-0562',
      latitude: '34.0621',
      longitude: '-118.283',
      geolong: '-118.282875',
      geolat: '34.06211618',
      reviews: [],
      rating: null,
    }]
  },
  {
    region: 'The Valley',
    parks: [{
      name: 'Andres and Maria Cardenas Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-valley/AndresAndMariaCardenas/andres-and-maria-cardenes1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/AndresAndMariaCardenas/andres-and-maria-cardenes2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/AndresAndMariaCardenas/andres-and-maria-cardenes3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/AndresAndMariaCardenas/andres-and-maria-cardenes4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/AndresAndMariaCardenas/andres-and-maria-cardenes5.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/AndresAndMariaCardenas/andres-and-maria-cardenes6.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/AndresAndMariaCardenas/andres-and-maria-cardenes7.jpg',
              ],
      address: {
        street: '14740 Blythe St',
        city: 'Panorama City',
        state: 'CA',
        zip: '91402'
      },
      region: 'valley',
      website: 'https://www.laparks.org/reccenter/andres-maria-ca%CC%81rdenas',
      phone: '(810) 781-3952',
      latitude: '34.215',
      longitude: '-118.455',
      geolong: '-118.454568',
      geolat: '34.215049',
      reviews: [],
      rating: null,
    },
    {
      name: 'Hansen Dam Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-valley/HansenDam/hansen-dam1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/HansenDam/hansen-dam2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/HansenDam/hansen-dam3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/HansenDam/hansen-dam4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/HansenDam/hansen-dam5.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/HansenDam/hansen-dam6.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/HansenDam/hansen-dam7.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/HansenDam/hansen-dam8.jpg',
              ],
      address: {
        street: '11770 Foothill Blvd',
        city: 'Lake View Terrace',
        state: 'CA',
        zip: '91342'
      },
      region: 'valley',
      website: 'https://www.laparks.org/skatepark/hansen-dam-skate',
      phone: '(818) 899-4537',
      latitude: '34.2738',
      longitude: '-118.383',
      geolong: '-118.383484',
      geolat: '34.273758',
      reviews: [],
      rating: null,
    },
    {
      name: 'Lanark Skate Plaza',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Lanark/lanark1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Lanark/lanark2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Lanark/lanark3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Lanark/lanark4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Lanark/lanark5.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Lanark/lanark6.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Lanark/lanark7.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Lanark/lanark8.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Lanark/lanark9.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Lanark/lanark10.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Lanark/lanark11.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Lanark/lanark12.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Lanark/lanark13.jpg',
              ],
      address: {
        street: '21816 Lanark St',
        city: 'Canoga Park',
        state: 'CA',
        zip: '91304'
      },
      region: 'valley',
      website: 'https://www.laparks.org/reccenter/lanark',
      phone: '(818) 883-1503',
      latitude: '34.2174',
      longitude: '-118.604',
      geolong: '-118.6038772',
      geolat: '34.21743314',
      reviews: [],
      rating: null,
    },
    {
      name: 'North Hollywood Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-valley/NorthHollywood/northhollywood1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/NorthHollywood/northhollywood2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/NorthHollywood/northhollywood3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/NorthHollywood/northhollywood4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/NorthHollywood/northhollywood5.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/NorthHollywood/northhollywood6.jpg',
              ],
      address: {
        street: '11430 Chandler Blvd',
        city: 'North Hollywood',
        state: 'CA',
        zip: '91601'
      },
      region: 'valley',
      website: 'https://www.laparks.org/skatepark/north-hollywood-skate',
      phone: '(818) 763-7651',
      latitude: '34.165',
      longitude: '-118.38',
      geolong: '-118.3799229',
      geolat: '34.1650083',
      reviews: [],
      rating: null,
    },
    {
      name: 'Pedlow Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Pedlow/pedlowskate1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Pedlow/pedlowskate2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Pedlow/pedlowskate3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Pedlow/pedlowskate4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Pedlow/pedlowskate5.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Pedlow/pedlowskate6.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Pedlow/pedlowskate7.jpg',
              ],
      address: {
        street: '17328 Victory Blvd',
        city: 'Lake Balboa',
        state: 'CA',
        zip: '91406'
      },
      region: 'valley',
      website: 'https://www.laparks.org/skatepark/pedlow-skate',
      phone: '(818) 654-5296',
      latitude: '34.1859',
      longitude: '-118.512',
      geolong: '-118.511611',
      geolat: '34.185931',
      reviews: [],
      rating: null,
    },
    {
      name: 'Ritchie Valens Skate Park Plaza',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-valley/RitchieValens/ritchie-valens1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/RitchieValens/ritchie-valens2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/RitchieValens/ritchie-valens3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/RitchieValens/ritchie-valens4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/RitchieValens/ritchie-valens5.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/RitchieValens/ritchie-valens6.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/RitchieValens/ritchie-valens7.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/RitchieValens/ritchie-valens8.jpg',
              ],
      address: {
        street: '10736 Laurel Canyon Blvd',
        city: 'Pacoima',
        state: 'CA',
        zip: '91331'
      },
      region: 'valley',
      website: 'https://www.laparks.org/reccenter/ritchie-valens',
      phone: '(818) 834-5172',
      latitude: '34.2651',
      longitude: '-118.439',
      geolong: '-118.4393469',
      geolat: '34.26510266',
      reviews: [],
      rating: null,
    },
    {
      name: 'Sheldon Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Sheldon/sheldon1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Sheldon/sheldon2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Sheldon/sheldon3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Sheldon/sheldon4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Sheldon/sheldon5.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Sheldon/sheldon6.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Sheldon/sheldon7.jpg',
              ],
      address: {
        street: '12511 Sheldon St',
        city: 'Sun Valley',
        state: 'CA',
        zip: '91352'
      },
      region: 'valley',
      website: 'https://www.laparks.org/skatepark/south-east-valley-skate-park-aka-sheldon-skate-park',
      phone: '(818) 756-8189',
      latitude: '34.231',
      longitude: '-118.406',
      geolong: '-118.405579',
      geolat: '34.230966',
      reviews: [],
      rating: null,
    },
    {
      name: 'Sunland Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Sunland/sunland1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Sunland/sunland2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-valley/Sunland/sunland3.jpg',
              ],
      address: {
        street: '8651 Foothill Blvd',
        city: 'Sunland',
        state: 'CA',
        zip: '91040'
      },
      region: 'valley',
      website: 'https://www.laparks.org/reccenter/sunland',
      phone: '(818) 352-5282',
      latitude: '34.2599',
      longitude: '-118.322',
      geolong: '-118.3220099',
      geolat: '34.25987785',
      reviews: [],
      rating: null,
    }]
  },
  {
    region: 'West LA',
    parks: [
    {
      name: 'Stoner Skater Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Stoner/stonerskate1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Stoner/stonerskate2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Stoner/stonerskate3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Stoner/stonerskate4.jpg',
              ],
      address: {
        street: '1835 Stoner Ave',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90025'
      },
      region: 'westLA',
      website: 'https://www.laparks.org/skatepark/stoner-skate',
      phone: '(310) 479-7200',
      latitude: '34.0384',
      longitude: '-118.453',
      geolong: '-118.4532902',
      geolat: '34.03844736',
      reviews: [],
      rating: null,
    },
    {
      name: 'Venice Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Venice/venicebeachskate9.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Venice/venicebeachskate1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Venice/venicebeachskate2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Venice/venicebeachskate3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Venice/venicebeachskate4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Venice/venicebeachskate5.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Venice/venicebeachskate6.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Venice/venicebeachskate7.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Venice/venicebeachskate8.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Venice/venicebeachskate10.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Venice/venicebeachskate11.jpg',
              ],
      address: {
        street: '1800 Ocean Front Walk',
        city: 'Venice',
        state: 'CA',
        zip: '90291'
      },
      region: 'westLA',
      website: 'https://www.laparks.org/skatepark/venice-skate',
      phone: '(310) 396-6794',
      latitude: '33.9857',
      longitude: '-118.473',
      geolong: '-118.4726212',
      geolat: '33.98570187',
      reviews: [],
      rating: null,
    },
    {
      name: 'Westchester Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Westchester/westchester1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Westchester/westchester2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Westchester/westchester3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-westla/Westchester/westchester4.jpg',
              ],
      address: {
        street: '7000 West Manchester Ave., Los Angeles, CA 90045',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90045'
      },
      region: 'westLA',
      website: 'https://www.laparks.org/skatepark/westchester-skate',
      phone: '(310) 670-7473',
      latitude: '33.9591',
      longitude: '-118.415',
      geolong: '-118.414785',
      geolat: '33.959143',
      reviews: [],
      rating: null,
    }]
  },
  {
    region: 'South LA',
    parks: [
    {
      name: 'Imperial Courts Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-southla/Imperial/imperialcourt1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southla/Imperial/imperialcourt2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southla/Imperial/imperialcourt3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southla/Imperial/imperialcourt4.jpg',
              ],
      address: {
        street: '2250 E. 114th St',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90059'
      },
      region: 'southLA',
      website: 'https://www.laparks.org/skatepark/imperial-courts-skate',
      phone: '(323) 564-1834',
      latitude: '33.9313',
      longitude: '-118.232',
      geolong: '-118.2324199',
      geolat: '33.93125654',
      reviews: [],
      rating: null,     
    },
    {
      name: 'Jackie Tatum Skate Plaza',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-southla/JackieTatum/jackietatumskate1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southla/JackieTatum/jackietatumskate2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southla/JackieTatum/jackietatumskate3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southla/JackieTatum/jackietatumskate4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southla/JackieTatum/jackietatumskate5.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southla/JackieTatum/jackietatumskate6.jpg',
              ],
      address: {
        street: '1535 West 62nd St',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90047'
      },
      region: 'southLA',
      website: 'https://www.laparks.org/skatepark/jackie-tatum-skate-plaza',
      phone: '(323) 778-2579',
      latitude: '33.9842',
      longitude: '-118.304',
      geolong: '-118.303512',
      geolat: '33.984177',
      reviews: [],
      rating: null,
    },
    {
      name: 'Nickerson Gardens Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-southla/Nickerson/nickerson1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southla/Nickerson/nickerson2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southla/Nickerson/nickerson3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southla/Nickerson/nickerson4.jpg',
              ],
      address: {
        street: '11251 Compton Ave',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90059'
      },
      region: 'southLA',
      website: '',
      phone: '(323) 566-0155',
      geolat: '33.932182',
      geolong: '-118.246727',
      latitude: '33.9322',
      longitude: '-118.247',
      reviews: [],
      rating: null, 

    },
    {
      name: 'Rancho Cienega Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-southla/RachoCienegaSkate/ranchociengeaskate1.jpg',
              ],
      address: {
        street: '5001 Obama Blvd',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90016'
      },
      region: 'southLA',
      website: 'https://www.laparks.org/skatepark/charmette-bonpua-aka-rancho-cienega-safe-spot-skate-spot',
      phone: '(323) 290-2663',
      latitude: '-118.352',
      longitude: '34.0217',
      geolong: '-118.351823',
      geolat: '34.02167021',
      reviews: [],
      rating: null,
    }]
  },
  {
    region: 'South Bay',
    parks: [
    { name: 'Harbor City Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-southbay/HarborCity/harbor-city1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southbay/HarborCity/harbor-city2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southbay/HarborCity/harbor-city3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southbay/HarborCity/harbor-city4.jpg',
              ],
      address: {
        street: '24901 Frampton Avenue',
        city: 'Harbor City',
        state: 'CA',
        zip: '90710'
      },
      region: 'southBay',
      website: 'https://www.laparks.org/skatepark/harbor-city-skate-park',
      phone: '(310) 548-7729',
      latitude: '',
      longitude: '',
      geolong: '',
      geolat: '',
      reviews: [],
      rating: null,
    },
    {
      name: 'Peck Park Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-southbay/Peck/peck1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southbay/Peck/peck2.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southbay/Peck/peck3.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southbay/Peck/peck4.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southbay/Peck/peck5.jpg',
              ],
      address: {
        street: '560 North Western Ave',
        city: 'San Pedro',
        state: 'CA',
        zip: '90732'
      },
      region: 'southBay',
      website: 'https://www.laparks.org/reccenter/peck-community',
      phone: '(310) 548-7580',
      latitude: '',
      longitude: '',
      geolong: '',
      geolat: '',
      reviews: [],
      rating: null,
    },
    {
      name: 'Wilmington (Ambassador) Skate Park',
      images: ['https://skateparks.s3-us-west-2.amazonaws.com/region-southbay/Wilmington/wilmingtonskate1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southbay/Wilmington/wilmingtonskate1.jpg',
              'https://skateparks.s3-us-west-2.amazonaws.com/region-southbay/Wilmington/wilmingtonskate1.jpg',
              ],
      address: {
        street: '325 Neptune Ave',
        city: 'Wilmington',
        state: 'CA',
        zip: '90744'
      },
      region: 'southBay',
      website: 'https://www.laparks.org/skatepark/wilmington-skate',
      phone: '(310) 548-7645',
      latitude: '33.7731',
      longitude: '-118.269',
      geolong: '-118.2686791',
      geolat: '33.77313982',
      reviews: [],
      rating: null,
    }]
  }
]

module.exports = dummyData;